name: Deploy Static Website to Azure Storage

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Upload files to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
          --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
          --destination '$web' \
          --source '.' \
          --overwrite